repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-aws-credentials
      - id: forbid-submodules
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
  - repo: https://github.com/pre-commit/mirrors-jshint
    rev: v2.13.6
    hooks:
      - id: jshint
        name: JavaScript Linter
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.16.0
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "terraform.docs.md", "./"]
        name: Terraform docs generation
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.2
    hooks:
      - id: terraform_fmt
        args: ["--args=-recursive"]
        name: Terraform canonical format reformat
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Python flake8 Linter
        args:
          [
            --count,
            "--select=E9,F63,F7,F82",
            --show-source,
            --statistics,
            --exit-zero,
            --max-complexity=10,
            --max-line-length=127,
          ]
