---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  An Amazon S3 Bucket configured as a static web site hosting.

Parameters:
  ProjectNameTag:
    Type: String
    Default: cloud-resume-challenge
    Description: Value used to indicate the resource as a part of the Cloud Resume Challenge

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "przepk-${ProjectNameTag}-website"
      WebsiteConfiguration:
        IndexDocument: index.html
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      Tags:
        - Key: project
          Value: !Sub ${ProjectNameTag}

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      PolicyDocument:
        Id: CloudResumeChallengeWebsiteBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join ["", ["arn:aws:s3:::", !Ref S3Bucket, /*]]
      Bucket: !Ref S3Bucket

  CloudResumeCFDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt S3Bucket.DomainName
            Id: cloudResumeS3Origin
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: cloudResumeS3Origin
          ViewerProtocolPolicy: redirect-to-https
          # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html
          CachePolicyId: b2884449-e4de-46a7-ac36-70bc7f1ddd6d
          AllowedMethods:
            - HEAD
            - GET
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
      Tags:
        - Key: project
          Value: !Sub ${ProjectNameTag}

  DynamoDBVisitorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "CounterName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "CounterName"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: !Sub "przepk-${ProjectNameTag}-website-visitors"
      Tags:
        - Key: project
          Value: !Sub ${ProjectNameTag}

Outputs:
  CloudResumeWebsiteURL:
    Value: !GetAtt S3Bucket.WebsiteURL
    Description: URL for static website hosted on Amazon S3
  CloudResumeSecureS3BucketURL:
    Value: !Join ["", ["https://", !GetAtt S3Bucket.DomainName]]
    Description: Name of the Cloud Resume S3 Bucket to hold static website content
  CloudResumeCFDomainName:
    Value:
      !Join ["", ["https://", !GetAtt CloudResumeCFDistribution.DomainName]]
    Description: Name of the Cloud Front distribution used to serve static website content
